[General]
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=8a5b9841-45f2-48e2-aac7-b2ddada97b72
Description=我的脚本1
Enable=0
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
'==========以下是按键精灵录制的内容==========
Delay 100

KeyDown "F", 1
Delay 125
KeyUp "F", 1


Delay 25000
KeyDown "F", 1
Delay 153
KeyUp "F", 1

'==========以上是按键精灵录制的内容==========
