[General]
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=660dbb46-be00-4534-a699-f57fc9cf94b4
Description=Jump Forward
Enable=0
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
'==========以下是按键精灵录制的内容==========

Delay 200
KeyDown "W", 1
Delay 16
KeyDown "Space", 1
Delay 219
KeyUp "Space", 1
Delay 31
KeyUp "W", 1
MoveTo 607, 494
Delay 200

'==========以上是按键精灵录制的内容==========
