[General]
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=72bb8b70-6757-4c4b-9fdc-7b5c0777fade
Description=rabbi >_>
Enable=0
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]

Call Roar



Sub Roar
	MessageBox "BRRRRAWWWWWWW"
	MessageBox "Nyan!"
End Sub
